[local]
localhost

[mongodb]
mongodb.daws90saws.shop

[redis]
redis.daws90saws.shop

[mysql]
mysql.daws90saws.shop

[rabbitmq]
rabbitmq.daws90saws.shop

[catalogue]
catalogue.daws90saws.shop

[user]
user.daws90saws.shop

[cart]
cart.daws90saws.shop